/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconButton: typeof import('./src/components/Feather/IconButton.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TAside: typeof import('tdesign-vue-next')['Aside'];
    TButton: typeof import('tdesign-vue-next')['Button'];
    TContent: typeof import('tdesign-vue-next')['Content'];
    THeader: typeof import('tdesign-vue-next')['Header'];
    TLayout: typeof import('tdesign-vue-next')['Layout'];
    ToolbarAction: typeof import('./src/components/Feather/toolbar-action.vue')['default'];
  }
}
