export const GET_WINDOW = 'GET_WINDOW';
export const OPEN_WINDOW = 'OPEN_WINDOW';

export const WINDOW_MINIMIZE = 'WINDOW_MINIMIZE';
export const WINDOW_MAXIMIZE = 'WINDOW_MAXIMIZE';
export const WINDOW_CLOSE = 'WINDOW_CLOSE';
